### ISSUE TITLE
breaking after upgrading to 0.11.0 from 0.4.3

### ISSUE THREAD

**Issue by mritunjayz** [excalidraw/excalidraw#4918]
have we removed `getElementMap` function from npm package? getting error `getElementMap is not a function` after updating to 0.11.0
 cc: @ad1992
